import Head from 'next/head'
import { Inter } from '@next/font/google'
import { AppShell, Navbar, Text, useMantineColorScheme } from '@mantine/core'
import TitlePage from '@/components/title-page'
import CertificationExperinceRequirements from '@/components/preflight-preperation/certification-experience-requirements'
import MainNavBar from '@/components/main-nav-bar'
import { CurrentSectionProvider } from '@/providers/CurrentSection'
import SectionRefWrapper from '@/util/section-ref-wrapper'
import GeneralPilotRequirements from '@/components/preflight-preperation/general-pilot-requirements'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { colorScheme } = useMantineColorScheme()

  return (
    <>
      <Head>
        <title>AirMx - IFR Cheatsheet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CurrentSectionProvider>
        <AppShell
          padding="md"
          navbar={
            <Navbar p="md" hiddenBreakpoint="sm" width={{ sm: 300, lg: 400 }}>
              <MainNavBar />
            </Navbar>
          }
        >
          <article className={`prose prose-slate ${colorScheme === `dark` ? `dark:prose-invert` : ``}`}>
            <TitlePage />
            <section id="bodymatter">
              <section id="preflight-preperation">
                <SectionRefWrapper sectionId="general-pilot-requirements">
                  <GeneralPilotRequirements />
                </SectionRefWrapper>
                <SectionRefWrapper sectionId="certification-experience-requirements">
                  <CertificationExperinceRequirements />
                </SectionRefWrapper>
              </section>
            </section>
          </article>
        </AppShell>
      </CurrentSectionProvider>
    </>
  )
}
